export { ReactComponent as Mail } from "ui-assets/icons/outline-email-24px.svg";
export { ReactComponent as Message } from "ui-assets/icons/outline-chat-24px.svg";
export { ReactComponent as Search } from "ui-assets/icons/outline-search-24px.svg";
export { ReactComponent as UserProfile } from "ui-assets/icons/outline-account_box-24px.svg";
export { ReactComponent as Location } from "ui-assets/icons/outline-location_on-24px.svg";
export { ReactComponent as Close } from "ui-assets/icons/outline-close-24px.svg";
export { ReactComponent as Info } from "ui-assets/icons/outline-info-24px.svg";
export { ReactComponent as Error } from "ui-assets/icons/outline-error-24px.svg";
export { ReactComponent as Home } from "ui-assets/icons/outline-home-24px.svg";
